### ISSUE TITLE
Relative CI stats not updated with Vite in the Github action

### ISSUE THREAD

**Issue by okomarov** [relative-ci/bundle-stats#4023]
We're using Vite and the following Github workflow:
```yaml
name: frontend
on:
  push:
    paths:
      - "apps/app/**"
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/app

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --prefer-frozen-lockfile
      - name: Build with stats
        run: pnpm build

      - name: Send bundle stats to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          webpackStatsFile: apps/app/build/webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
where the build command is: `"build": "tsc && vite build"`

When I check the step in the Github workflow, the printed stats are actually up-to-date and so is the produced `webpack-stats.json`. The Relative CI agent however reports older stats.

<img width="1024" alt="image" src="https://github.com/relative-ci/bundle-stats/assets/3731173/7407281e-c6fd-4f00-9f14-4cb5dc7dfc83">
